//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.0.8.0 (NJsonSchema v11.0.1.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming

import {
  mergeMap as _observableMergeMap,
  catchError as _observableCatch,
} from 'rxjs/operators';
import {
  Observable,
  throwError as _observableThrow,
  of as _observableOf,
} from 'rxjs';
import { Injectable, Inject, Optional, InjectionToken } from '@angular/core';
import {
  HttpClient,
  HttpHeaders,
  HttpResponse,
  HttpResponseBase,
} from '@angular/common/http';

export const API_BASE_URL = new InjectionToken<string>('API_BASE_URL');

@Injectable({
  providedIn: 'root',
})
export class BrowseCardControllerClient {
  private http: HttpClient;
  private baseUrl: string;
  protected jsonParseReviver: ((key: string, value: any) => any) | undefined =
    undefined;

  constructor(
    @Inject(HttpClient) http: HttpClient,
    @Optional() @Inject(API_BASE_URL) baseUrl?: string
  ) {
    this.http = http;
    this.baseUrl = baseUrl ?? 'http://localhost:8080';
  }

  /**
   * @param size (optional)
   * @return OK
   */
  totalPages(size: number | undefined): Observable<number> {
    let url_ = this.baseUrl + '/browse/totalPages?';
    if (size === null) throw new Error("The parameter 'size' cannot be null.");
    else if (size !== undefined)
      url_ += 'size=' + encodeURIComponent('' + size) + '&';
    url_ = url_.replace(/[?&]$/, '');

    let options_: any = {
      observe: 'response',
      responseType: 'blob',
      headers: new HttpHeaders({
        Accept: '*/*',
      }),
    };

    return this.http
      .request('get', url_, options_)
      .pipe(
        _observableMergeMap((response_: any) => {
          return this.processTotalPages(response_);
        })
      )
      .pipe(
        _observableCatch((response_: any) => {
          if (response_ instanceof HttpResponseBase) {
            try {
              return this.processTotalPages(response_ as any);
            } catch (e) {
              return _observableThrow(e) as any as Observable<number>;
            }
          } else
            return _observableThrow(response_) as any as Observable<number>;
        })
      );
  }

  protected processTotalPages(response: HttpResponseBase): Observable<number> {
    const status = response.status;
    const responseBlob =
      response instanceof HttpResponse
        ? response.body
        : (response as any).error instanceof Blob
        ? (response as any).error
        : undefined;

    let _headers: any = {};
    if (response.headers) {
      for (let key of response.headers.keys()) {
        _headers[key] = response.headers.get(key);
      }
    }
    if (status === 200) {
      return blobToText(responseBlob).pipe(
        _observableMergeMap((_responseText: string) => {
          let result200: any = null;
          let resultData200 =
            _responseText === ''
              ? null
              : JSON.parse(_responseText, this.jsonParseReviver);
          result200 = resultData200 !== undefined ? resultData200 : <any>null;

          return _observableOf(result200);
        })
      );
    } else if (status !== 200 && status !== 204) {
      return blobToText(responseBlob).pipe(
        _observableMergeMap((_responseText: string) => {
          return throwException(
            'An unexpected server error occurred.',
            status,
            _responseText,
            _headers
          );
        })
      );
    }
    return _observableOf(null as any);
  }

  /**
   * @return OK
   */
  search(query: string): Observable<Card[]> {
    let url_ = this.baseUrl + '/browse/search?';
    if (query === undefined || query === null)
      throw new Error(
        "The parameter 'query' must be defined and cannot be null."
      );
    else url_ += 'query=' + encodeURIComponent('' + query) + '&';
    url_ = url_.replace(/[?&]$/, '');

    let options_: any = {
      observe: 'response',
      responseType: 'blob',
      headers: new HttpHeaders({
        Accept: '*/*',
      }),
    };

    return this.http
      .request('get', url_, options_)
      .pipe(
        _observableMergeMap((response_: any) => {
          return this.processSearch(response_);
        })
      )
      .pipe(
        _observableCatch((response_: any) => {
          if (response_ instanceof HttpResponseBase) {
            try {
              return this.processSearch(response_ as any);
            } catch (e) {
              return _observableThrow(e) as any as Observable<Card[]>;
            }
          } else
            return _observableThrow(response_) as any as Observable<Card[]>;
        })
      );
  }

  protected processSearch(response: HttpResponseBase): Observable<Card[]> {
    const status = response.status;
    const responseBlob =
      response instanceof HttpResponse
        ? response.body
        : (response as any).error instanceof Blob
        ? (response as any).error
        : undefined;

    let _headers: any = {};
    if (response.headers) {
      for (let key of response.headers.keys()) {
        _headers[key] = response.headers.get(key);
      }
    }
    if (status === 200) {
      return blobToText(responseBlob).pipe(
        _observableMergeMap((_responseText: string) => {
          let result200: any = null;
          let resultData200 =
            _responseText === ''
              ? null
              : JSON.parse(_responseText, this.jsonParseReviver);
          if (Array.isArray(resultData200)) {
            result200 = [] as any;
            for (let item of resultData200) result200!.push(Card.fromJS(item));
          } else {
            result200 = <any>null;
          }
          return _observableOf(result200);
        })
      );
    } else if (status !== 200 && status !== 204) {
      return blobToText(responseBlob).pipe(
        _observableMergeMap((_responseText: string) => {
          return throwException(
            'An unexpected server error occurred.',
            status,
            _responseText,
            _headers
          );
        })
      );
    }
    return _observableOf(null as any);
  }

  /**
   * @param page (optional)
   * @param size (optional)
   * @return OK
   */
  page(page: number | undefined, size: number | undefined): Observable<Card[]> {
    let url_ = this.baseUrl + '/browse/page?';
    if (page === null) throw new Error("The parameter 'page' cannot be null.");
    else if (page !== undefined)
      url_ += 'page=' + encodeURIComponent('' + page) + '&';
    if (size === null) throw new Error("The parameter 'size' cannot be null.");
    else if (size !== undefined)
      url_ += 'size=' + encodeURIComponent('' + size) + '&';
    url_ = url_.replace(/[?&]$/, '');

    let options_: any = {
      observe: 'response',
      responseType: 'blob',
      headers: new HttpHeaders({
        Accept: '*/*',
      }),
    };

    return this.http
      .request('get', url_, options_)
      .pipe(
        _observableMergeMap((response_: any) => {
          return this.processPage(response_);
        })
      )
      .pipe(
        _observableCatch((response_: any) => {
          if (response_ instanceof HttpResponseBase) {
            try {
              return this.processPage(response_ as any);
            } catch (e) {
              return _observableThrow(e) as any as Observable<Card[]>;
            }
          } else
            return _observableThrow(response_) as any as Observable<Card[]>;
        })
      );
  }

  protected processPage(response: HttpResponseBase): Observable<Card[]> {
    const status = response.status;
    const responseBlob =
      response instanceof HttpResponse
        ? response.body
        : (response as any).error instanceof Blob
        ? (response as any).error
        : undefined;

    let _headers: any = {};
    if (response.headers) {
      for (let key of response.headers.keys()) {
        _headers[key] = response.headers.get(key);
      }
    }
    if (status === 200) {
      return blobToText(responseBlob).pipe(
        _observableMergeMap((_responseText: string) => {
          let result200: any = null;
          let resultData200 =
            _responseText === ''
              ? null
              : JSON.parse(_responseText, this.jsonParseReviver);
          if (Array.isArray(resultData200)) {
            result200 = [] as any;
            for (let item of resultData200) result200!.push(Card.fromJS(item));
          } else {
            result200 = <any>null;
          }
          return _observableOf(result200);
        })
      );
    } else if (status !== 200 && status !== 204) {
      return blobToText(responseBlob).pipe(
        _observableMergeMap((_responseText: string) => {
          return throwException(
            'An unexpected server error occurred.',
            status,
            _responseText,
            _headers
          );
        })
      );
    }
    return _observableOf(null as any);
  }
}

export class Card implements ICard {
  id?: string;
  oracle_id?: string;
  multiverse_ids?: number[];
  mtgo_id?: number;
  set_id?: string;
  name?: string;
  released_at?: string;
  uri?: string;
  scryfall_uri?: string;
  image_uris?: ImageUris;
  mana_cost?: string;
  cmc?: number;
  type_line?: string;
  oracle_text?: string;
  power?: string;
  toughness?: string;
  colors?: string[];
  color_identity?: string[];
  keywords?: string[];
  set?: string;
  set_name?: string;
  set_type?: string;
  rarity?: string;
  prices?: Prices;

  [key: string]: any;

  constructor(data?: ICard) {
    if (data) {
      for (var property in data) {
        if (data.hasOwnProperty(property))
          (<any>this)[property] = (<any>data)[property];
      }
    }
  }

  init(_data?: any) {
    if (_data) {
      for (var property in _data) {
        if (_data.hasOwnProperty(property)) this[property] = _data[property];
      }
      this.id = _data['id'];
      this.oracle_id = _data['oracle_id'];
      if (Array.isArray(_data['multiverse_ids'])) {
        this.multiverse_ids = [] as any;
        for (let item of _data['multiverse_ids'])
          this.multiverse_ids!.push(item);
      }
      this.mtgo_id = _data['mtgo_id'];
      this.set_id = _data['set_id'];
      this.name = _data['name'];
      this.released_at = _data['released_at'];
      this.uri = _data['uri'];
      this.scryfall_uri = _data['scryfall_uri'];
      this.image_uris = _data['image_uris']
        ? ImageUris.fromJS(_data['image_uris'])
        : <any>undefined;
      this.mana_cost = _data['mana_cost'];
      this.cmc = _data['cmc'];
      this.type_line = _data['type_line'];
      this.oracle_text = _data['oracle_text'];
      this.power = _data['power'];
      this.toughness = _data['toughness'];
      if (Array.isArray(_data['colors'])) {
        this.colors = [] as any;
        for (let item of _data['colors']) this.colors!.push(item);
      }
      if (Array.isArray(_data['color_identity'])) {
        this.color_identity = [] as any;
        for (let item of _data['color_identity'])
          this.color_identity!.push(item);
      }
      if (Array.isArray(_data['keywords'])) {
        this.keywords = [] as any;
        for (let item of _data['keywords']) this.keywords!.push(item);
      }
      this.set = _data['set'];
      this.set_name = _data['set_name'];
      this.set_type = _data['set_type'];
      this.rarity = _data['rarity'];
      this.prices = _data['prices']
        ? Prices.fromJS(_data['prices'])
        : <any>undefined;
    }
  }

  static fromJS(data: any): Card {
    data = typeof data === 'object' ? data : {};
    let result = new Card();
    result.init(data);
    return result;
  }

  toJSON(data?: any) {
    data = typeof data === 'object' ? data : {};
    for (var property in this) {
      if (this.hasOwnProperty(property)) data[property] = this[property];
    }
    data['id'] = this.id;
    data['oracle_id'] = this.oracle_id;
    if (Array.isArray(this.multiverse_ids)) {
      data['multiverse_ids'] = [];
      for (let item of this.multiverse_ids) data['multiverse_ids'].push(item);
    }
    data['mtgo_id'] = this.mtgo_id;
    data['set_id'] = this.set_id;
    data['name'] = this.name;
    data['released_at'] = this.released_at;
    data['uri'] = this.uri;
    data['scryfall_uri'] = this.scryfall_uri;
    data['image_uris'] = this.image_uris
      ? this.image_uris.toJSON()
      : <any>undefined;
    data['mana_cost'] = this.mana_cost;
    data['cmc'] = this.cmc;
    data['type_line'] = this.type_line;
    data['oracle_text'] = this.oracle_text;
    data['power'] = this.power;
    data['toughness'] = this.toughness;
    if (Array.isArray(this.colors)) {
      data['colors'] = [];
      for (let item of this.colors) data['colors'].push(item);
    }
    if (Array.isArray(this.color_identity)) {
      data['color_identity'] = [];
      for (let item of this.color_identity) data['color_identity'].push(item);
    }
    if (Array.isArray(this.keywords)) {
      data['keywords'] = [];
      for (let item of this.keywords) data['keywords'].push(item);
    }
    data['set'] = this.set;
    data['set_name'] = this.set_name;
    data['set_type'] = this.set_type;
    data['rarity'] = this.rarity;
    data['prices'] = this.prices ? this.prices.toJSON() : <any>undefined;
    return data;
  }
}

export interface ICard {
  id?: string;
  oracle_id?: string;
  multiverse_ids?: number[];
  mtgo_id?: number;
  set_id?: string;
  name?: string;
  released_at?: string;
  uri?: string;
  scryfall_uri?: string;
  image_uris?: ImageUris;
  mana_cost?: string;
  cmc?: number;
  type_line?: string;
  oracle_text?: string;
  power?: string;
  toughness?: string;
  colors?: string[];
  color_identity?: string[];
  keywords?: string[];
  set?: string;
  set_name?: string;
  set_type?: string;
  rarity?: string;
  prices?: Prices;

  [key: string]: any;
}

export class ImageUris implements IImageUris {
  small?: string;
  normal?: string;
  large?: string;
  png?: string;
  art_crop?: string;
  border_crop?: string;

  [key: string]: any;

  constructor(data?: IImageUris) {
    if (data) {
      for (var property in data) {
        if (data.hasOwnProperty(property))
          (<any>this)[property] = (<any>data)[property];
      }
    }
  }

  init(_data?: any) {
    if (_data) {
      for (var property in _data) {
        if (_data.hasOwnProperty(property)) this[property] = _data[property];
      }
      this.small = _data['small'];
      this.normal = _data['normal'];
      this.large = _data['large'];
      this.png = _data['png'];
      this.art_crop = _data['art_crop'];
      this.border_crop = _data['border_crop'];
    }
  }

  static fromJS(data: any): ImageUris {
    data = typeof data === 'object' ? data : {};
    let result = new ImageUris();
    result.init(data);
    return result;
  }

  toJSON(data?: any) {
    data = typeof data === 'object' ? data : {};
    for (var property in this) {
      if (this.hasOwnProperty(property)) data[property] = this[property];
    }
    data['small'] = this.small;
    data['normal'] = this.normal;
    data['large'] = this.large;
    data['png'] = this.png;
    data['art_crop'] = this.art_crop;
    data['border_crop'] = this.border_crop;
    return data;
  }
}

export interface IImageUris {
  small?: string;
  normal?: string;
  large?: string;
  png?: string;
  art_crop?: string;
  border_crop?: string;

  [key: string]: any;
}

export class Prices implements IPrices {
  usd?: string;
  usd_foil?: string;
  usd_etched?: string;
  eur?: string;
  eur_foil?: string;
  tix?: string;

  [key: string]: any;

  constructor(data?: IPrices) {
    if (data) {
      for (var property in data) {
        if (data.hasOwnProperty(property))
          (<any>this)[property] = (<any>data)[property];
      }
    }
  }

  init(_data?: any) {
    if (_data) {
      for (var property in _data) {
        if (_data.hasOwnProperty(property)) this[property] = _data[property];
      }
      this.usd = _data['usd'];
      this.usd_foil = _data['usd_foil'];
      this.usd_etched = _data['usd_etched'];
      this.eur = _data['eur'];
      this.eur_foil = _data['eur_foil'];
      this.tix = _data['tix'];
    }
  }

  static fromJS(data: any): Prices {
    data = typeof data === 'object' ? data : {};
    let result = new Prices();
    result.init(data);
    return result;
  }

  toJSON(data?: any) {
    data = typeof data === 'object' ? data : {};
    for (var property in this) {
      if (this.hasOwnProperty(property)) data[property] = this[property];
    }
    data['usd'] = this.usd;
    data['usd_foil'] = this.usd_foil;
    data['usd_etched'] = this.usd_etched;
    data['eur'] = this.eur;
    data['eur_foil'] = this.eur_foil;
    data['tix'] = this.tix;
    return data;
  }
}

export interface IPrices {
  usd?: string;
  usd_foil?: string;
  usd_etched?: string;
  eur?: string;
  eur_foil?: string;
  tix?: string;

  [key: string]: any;
}

export class ApiException extends Error {
  override message: string;
  status: number;
  response: string;
  headers: { [key: string]: any };
  result: any;

  constructor(
    message: string,
    status: number,
    response: string,
    headers: { [key: string]: any },
    result: any
  ) {
    super();

    this.message = message;
    this.status = status;
    this.response = response;
    this.headers = headers;
    this.result = result;
  }

  protected isApiException = true;

  static isApiException(obj: any): obj is ApiException {
    return obj.isApiException === true;
  }
}

function throwException(
  message: string,
  status: number,
  response: string,
  headers: { [key: string]: any },
  result?: any
): Observable<any> {
  if (result !== null && result !== undefined) return _observableThrow(result);
  else
    return _observableThrow(
      new ApiException(message, status, response, headers, null)
    );
}

function blobToText(blob: any): Observable<string> {
  return new Observable<string>((observer: any) => {
    if (!blob) {
      observer.next('');
      observer.complete();
    } else {
      let reader = new FileReader();
      reader.onload = (event) => {
        observer.next((event.target as any).result);
        observer.complete();
      };
      reader.readAsText(blob);
    }
  });
}
